// Random Debate Website/src/components/DebateTimer.tsx
import { Clock } from 'lucide-react';
import { Badge } from './ui/badge';

type DebateTimerProps = {
  timeRemaining: number;
  isRunning: boolean;
};

export function DebateTimer({ timeRemaining, isRunning }: DebateTimerProps) {
  const formatTime = (seconds: number) => {
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;
    return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
  };

  const getTimeColor = () => {
    if (timeRemaining <= 60) return 'destructive'; // Last minute
    if (timeRemaining <= 180) return 'secondary'; // Last 3 minutes
    return 'default';
  };

  const getTimeStatus = () => {
    if (!isRunning && timeRemaining > 0) return 'Paused';
    if (timeRemaining <= 0) return 'Time Up!';
    return 'Active';
  };

  return (
    <div className="flex items-center gap-3">
      <div className="flex items-center gap-2">
        <Clock className={`w-5 h-5 ${isRunning ? 'animate-pulse' : ''}`} />
        <div className="text-right">
          <div className="font-mono text-lg font-medium">
            {formatTime(timeRemaining)}
          </div>
          <div className="text-xs text-muted-foreground">
            {getTimeStatus()}
          </div>
        </div>
      </div>
      
      <Badge variant={getTimeColor()}>
        {timeRemaining <= 0 ? 'Finished' : isRunning ? 'Running' : 'Paused'}
      </Badge>
    </div>
  );
}

// devate-front/src/components/DebateTimer.vue
<template>
    <div class="flex items-center gap-3">
        <div class="flex items-center gap-2">
            <Clock :class="`w-5 h-5 ${isRunning ? 'animate-pulse' : ''}`" />
            <div class="text-right">
                <div class="font-mono text-lg font-medium">{{ formattedTime }}</div>
                <div class="text-xs text-muted-foreground">{{ statusText }}</div>
            </div>
        </div>

        <Badge :variant="timeColor">
            {{ badgeText }}
        </Badge>
    </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { Clock } from 'lucide-vue-next';
import { Badge } from './ui/badge';

interface Props {
    timeRemaining: number;
    isRunning: boolean;
}

const props = defineProps<Props>();

const formattedTime = computed(() => {
    const minutes = Math.floor(props.timeRemaining / 60);
    const seconds = props.timeRemaining % 60;
    return `${minutes}:${seconds.toString().padStart(2, '0')}`;
});

const timeColor = computed(() => {
    if (props.timeRemaining <= 60) return 'destructive';
    if (props.timeRemaining <= 180) return 'secondary';
    return 'default';
});

const statusText = computed(() => {
    if (!props.isRunning && props.timeRemaining > 0) return 'Paused';
    if (props.timeRemaining <= 0) return 'Time Up!';
    return 'Active';
});

const badgeText = computed(() => {
    if (props.timeRemaining <= 0) return 'Finished';
    return props.isRunning ? 'Running' : 'Paused';
});
</script>
